import React,{useState} from "react";
import {Routes,Route,Link} from "react-router-dom";
import {Dash,Stat} from "../components/Site";
import {lands} from "../data";
const nav=[["/landowner","Dashboard","bi-grid-1x2-fill"],["/landowner/lands","My Lands","bi-map"],["/landowner/add-land","Add Land","bi-plus-square"],["/landowner/requests","Lease Requests","bi-file-earmark-text"],["/landowner/profile","Profile","bi-person"],["/landowner/logout","Logout","bi-box-arrow-right"]];
const Card=({title,children,action})=><div className="dash-card"><div className="dash-card-head"><h6>{title}</h6>{action}</div>{children}</div>;
const Requests=()=> <div className="table-responsive"><table className="table"><thead><tr><th>Farmer</th><th>Area</th><th>Location</th><th>Status</th><th>Action</th></tr></thead><tbody>{[["Ramesh","5 Acres","Guntur"],["Suresh","3 Acres","Nellore"],["Mahesh","10 Acres","Prakasam"]].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className="badge-soft">Pending</span></td><td><button className="btn btn-sm btn-success">Review</button></td></tr>)}</tbody></table></div>;
function Home(){return <><div className="welcome"><div><span className="eyebrow">LANDOWNER WORKSPACE</span><h2>Welcome, Landowner! 🌾</h2><p>Manage land listings and lease opportunities.</p></div></div><div className="row g-3 mb-4">{[["bi-map","4","Total Lands"],["bi-check-circle","2","Active Lands"],["bi-hourglass-split","3","Pending Requests"]].map(x=><div className="col-md-4" key={x[2]}><Stat icon={x[0]} value={x[1]} label={x[2]}/></div>)}</div><Card title="Recent Lease Requests" action={<Link to="/landowner/requests">View All</Link>}><Requests/></Card></>}
function Lands(){return <Card title="My Land Listings" action={<Link className="btn btn-sm btn-success" to="/landowner/add-land">Add Land</Link>}><div className="row g-3">{lands.map(l=><div className="col-md-6" key={l.id}><div className="mini-land"><img src={l.image} alt=""/><div><b>{l.location}</b><span className="badge-soft float-end">{l.status}</span><small>{l.area} Acres · ₹{l.price.toLocaleString()}/year</small><div className="mt-2"><button className="btn btn-sm btn-outline-secondary me-1">Edit</button><button className="btn btn-sm btn-outline-danger">Delete</button></div></div></div></div>)}</div></Card>}
function AddLand(){const[done,setDone]=useState(false);return <Card title="Add Land"><form className="row g-3" onSubmit={e=>{e.preventDefault();setDone(true)}}>{["Location","Land Type","Area (acres)","Price / Year"].map(x=><div className="col-md-6" key={x}><label>{x}</label><input required className="form-control" placeholder={x}/></div>)}<div className="col-12"><label>Description</label><textarea className="form-control" rows="4"/></div><div className="col-12"><label>Upload Images</label><input type="file" multiple className="form-control"/></div><div><button className="btn btn-success px-4">Submit</button></div></form>{done&&<div className="alert alert-success mt-3">Land listing submitted.</div>}</Card>}
function Profile(){return <Card title="Profile"><form className="row g-3">{["Full Name","Email","Phone","Location"].map(x=><div className="col-md-6" key={x}><label>{x}</label><input className="form-control" defaultValue={x==="Full Name"?"Anita":x==="Email"?"anita@gmail.com":x==="Location"?"Andhra Pradesh":""}/></div>)}<div><button className="btn btn-success">Update Profile</button></div></form></Card>}
export default function Landowner(){return <Dash role="Landowner" title="Landowner Dashboard" items={nav}><Routes><Route index element={<Home/>}/><Route path="lands" element={<Lands/>}/><Route path="add-land" element={<AddLand/>}/><Route path="requests" element={<Card title="Lease Requests"><Requests/></Card>}/><Route path="profile" element={<Profile/>}/></Routes></Dash>}